# Generated by Django 4.2.1 on 2023-05-11 04:02

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=350)),
                ('profile_image', models.ImageField(upload_to='static/images/profile')),
                ('long_description', django_quill.fields.QuillField(null=True)),
                ('fb_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
            ],
        ),
    ]
